version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
      # Replace the path below with your actual local path
      - ~/Project3_n8n:/data/repo:rw
    command: /bin/sh -c "apk add --no-cache git nodejs npm && npm install -g promptfoo && n8n start"

volumes:
  n8n_data: